export const EmptyProfileModel = {
  candidateID: "",
  fullName: "",
  jobTitle: "",
  companyName: "",
  location: "",
  experience: "",
  salary: "",
  mobileNumber: "",
  email: "",
  availabilityToJoin: "1month",
  education: {
    educationType: "",
    university: "",
    course: "",
    courseType: "Full time",
    specialization: "",
    duration: "",
    percentage: "",
  },
  employment: {
    isCurrentEmployement: false,
    employmentType: "fulltime",
  },
  personalDetails: {
    gender: "male",
    maritalStatus: "unmarried",
    dob: "",
    category: "general",
    abled: false,
    type: "",
    workplaceAssistance: "",
    address: "",
    city: "",
    pincode: "",
  },
};
