export const EmptyProfileModel = {
  candidateID: "",
  fullName: "",
  jobTitle: "",
  companyName: "",
  location: "",
  experience: "",
  salary: "",
  mobileNumber: "",
  email: "",
  availabilityToJoin: "",
  employment: {
    isCurrentEmployement: false,
    employmentType: "",
    personalDetails: {
      gender: "",
      maritalStatus: "",
      dob: "",
      category: "",
      abled: false,
      type: "",
      workplaceAssistance: "",
      address: "",
      city: "",
      pincode: "",
    },
  },
};
