export const EmptyProfileModel = {
  candidateID: "",
  fullName: "",
  jobTitle: "",
  companyName: "",
  location: "",
  experience: "",
  salary: "",
  mobileNumber: "",
  email: "",
  availabilityToJoin: "1month",
  employment: {
    isCurrentEmployement: false,
    employmentType: "fulltime",
    personalDetails: {
      gender: "male",
      maritalStatus: "unmarried",
      dob: "",
      category: "general",
      abled: false,
      type: "",
      workplaceAssistance: "",
      address: "",
      city: "",
      pincode: "",
    },
  },
};
